import Head from "next/head";
import HeroPage from "../pages/heroPage";
import Technologies from "./technologies";
import Services from "./services";
import Vision from "./vision";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Computer Technology Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='https://www.svgrepo.com/show/225051/cpu.svg' />
      </Head>
      <HeroPage />
      <Services />
      <Vision />
      <Technologies />
      <Contact />
    </div>
  );
}
